django-salesforce/django-salesforce

README.rst

Thanks for the great Django module.
I've struggled today getting the authorisation to work with Salesforce, primarily because I'm not familiar with their API and docs. I found all the info I needed in this closed issue: https://github.com/django-salesforce/django-salesforce/issues/83
As per the suggestion there, I've added this info to the quick start in README. Hopefully it'll help other Djangonauts who don't know Salesforce well in the future.

Expanding README with auth info

---

.gitignore
README.rst
requirements.txt
salesforce/tests/__init__.py
salesforce/tests/test_utils.py
salesforce/utils.py

A new utility module that adds support for the Salesforce SOAP API in order to take advantage of the missing endpoints in the REST API (such as convertLead).
This feature requires an additional dependency as we use a third-party module to talk to the SOAP API: [beatbox](https://pypi.python.org/pypi/beatbox/32.1). However, this dependency is totally optional for users who do not need more than the capabilities offered by the REST API.
Launch the unit test with
```
./manage.py test salesforce.tests.test_utils
```

Integration of convertLead() from the SOAP API using beatbox

---

README.rst
salesforce/__init__.py
salesforce/auth.py
salesforce/backend/__init__.py
salesforce/backend/adapter.py
salesforce/backend/base.py
salesforce/backend/compiler.py
salesforce/backend/introspection.py
salesforce/backend/query.py
salesforce/fields.py
salesforce/management/commands/inspectdb.py
salesforce/models.py
salesforce/testrunner/example/admin.py
salesforce/testrunner/example/models.py
salesforce/testrunner/example/universal_admin.py
salesforce/tests/test_auth.py
salesforce/tests/test_integration.py
salesforce/tests/test_utils.py
tests/inspectdb/admin.py
tests/inspectdb/slow_test.py
tests/inspectdb/test.sh
tests/inspectdb/tests.py
tests/test_compatibility/models.py
tests/test_compatibility/tests.py
tox.ini

This is a cumulative pull request with finished more than a half of my development since November.
- It is possible to write filters with more foreign keys related to the same model..
- More compatibility with standard Django + migrations (no real migrations, but very useful if the development is done on any standard Django database), serializable default values etc.
- Improved introspection, supported DEFAULTED_ON_CREATE, better comments to exported models, complete compatibility betwen Python 2 and 3.
- Fixed SSL protocol settings to current security requirements

Cumulative change: Queries based on more ForeignKeys to the same table etc

---

README.rst
salesforce/backend/adapter.py
salesforce/backend/compiler.py
salesforce/backend/introspection.py
salesforce/backend/query.py
salesforce/management/commands/inspectdb.py
salesforce/testrunner/example/models.py
salesforce/tests/__init__.py
salesforce/tests/test_auth.py
salesforce/tests/test_integration.py
salesforce/tests/test_ssl.py
salesforce/tests/test_utils.py
salesforce/tests/utils.py
tests/inspectdb/slow_test.py
tox.ini

Much documentation together with code
If the test of TLS 1.1+ fails and no upgrade is possible, it can be skipped by
settings.py
SF_SSL = {'skiptest_tls_11': True, ...}

Some fixes for Django 1.8, Tests for SSL, filter with similar FK etc

---

.travis.yml
salesforce/testrunner/settings.py

This writes a local_settings.py file to setup sslv23 rather than install PyOpenSSL, as Travis is currently running Python 2.7.9 for its build.

Set SSLv23 for Travis builds only

---

salesforce/backend/query.py
salesforce/tests/test_integration.py

The patch in "SalesforceQuerySet.iterator" imitates
"django.db.models.sql.compiler.SQLCompiler" that does the same for normal
backends, but in 1 method instead of 3 nested layers.
We have no more similar hooks for this (in Django 1.8):
django/db/models/query.py(254) QuerySet.iterator()
-> for row in compiler.results_iter():
django/db/models/sql/compiler.py(783) SQLCompiler.results_iter()
-> for rows in self.execute_sql(MULTI):
> django/db/models/sql/compiler.py(821) SQLCompiler.execute_sql()
except EmptyResultSet:

Fixed EmptyResultSet error after none() method in queryset. Closes #124

---

README.rst
salesforce/auth.py
salesforce/backend/__init__.py
salesforce/backend/base.py
salesforce/backend/compiler.py
salesforce/backend/query.py
salesforce/backend/subselect.py
salesforce/testrunner/example/models.py
salesforce/tests/test_integration.py
salesforce/tests/test_utils.py
tests/inspectdb/slow_test.py
tests/test_lazy_connect/tests.py

- Implemented Many2many realtionship so that the related name .all() and the reverse related name .all() works, with Django 1.4 to 1.8
- Speed up tests. The connection to SFDC is not created until necessary, because some tests don't require the connection at all.
closes #103, #124

Many2many relationship, advanced Where conditions

---

salesforce/backend/compiler.py
salesforce/tests/__init__.py
salesforce/tests/test_integration.py
salesforce/tests/test_unit.py
salesforce/tests/test_utils.py
salesforce/tests/utils.py
tests/test_compatibility/tests.py
tests/test_mixin/tests.py

I think it is an important fix and a big part of issues is now ready. The standard result is currently 5 skipped tests for SSL.
I also have sometimes the problem that while long queue of tests is running I need to try one short test. I improved it again.
Other important fix will be query_results method of query. I can continue in September.

Fixed query compiler

---

salesforce/backend/compiler.py
salesforce/testrunner/example/models.py
salesforce/tests/test_integration.py

This pull request modifies the range lookup provided by Django to render the correct SOQL code for the Salesforce API.  The reason this is needed is that Salesforce does not recognize the BETWEEN clause in SOQL.
Prior to this pull request:
```
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
opportunities = Opportunity.objects.filter(close_date__range(yesterday, today))
```
generated this SQL:
```
'SELECT <<my_opportunity_fields>> FROM Opportunity WHERE Opportunity.close_date BETWEEN %s AND %s', (datetime.date(2015, 9, 1), datetime.date(2015, 9, 2))
```
This pull request now renders this SOQL:
```
'SELECT <<my_opportunity_fields>> FROM Opportunity WHERE Opportunity.close_date >= %s AND Opportunity.close_date <= %s', (datetime.date(2015, 9, 1), …
```

add range lookup functionality

---

README.rst
wiki/Experimental-Features.rest
wiki/Foreign-Key-Support.rest
wiki/Home.md
wiki/Introspection-and-Special-Attributes-of-Fields.rest
wiki/SSL-TLS-settings-and-Saleforce.com.rest

I found a bug that [our README on pypi](https://pypi.python.org/pypi/django-salesforce/0.6.2) is without formating again due to invalid syntax caused by some missing whitespace. I really should not edit the README so frequently as now.
I rebased my changes to README made in September by me concurrently with your #134. I have merged both now.
I also copied the shaphost of github.com/django-salesforce Wiki to `./wiki` directory. I need it for the development of new features in development branches until they are ready to be published and merged to master. Wiki pages for the current code can be naturally written and fixed directly by github web. I will synchronize them before any push from wiki directory to wiki web.

Migrate some README to Wiki

---

salesforce/tests/test_utils.py

The older setting `SF_PK='Id'` is probably still easier for people who use also other developer tools and other API or a raw SOQL for work with Salesforce. This convention is not The default `SF_PK='id'` is preferable for people who mostly use only Django-salesforce. I also try both if I am developing something in the compiler because I believe that it helps to find subtle bugs and misconception before committing. Sometimes it saves a development on new idea that initially works only with one of these settings.

Fixed test to work with both possible SF_PK id/Id.

---

README.rst
salesforce/backend/compiler.py
salesforce/testrunner/example/universal_admin.py
salesforce/tests/test_integration.py
wiki/Error-messages.md
wiki/Experimental-Features.rest
wiki/Foreign-Key-Support.rest
wiki/Introspection-and-Special-Attributes-of-Fields.rest

small updates
- improved the automatic admin so that it can be used for the first experiments in quick start readme.
- clear error message for one-to-one field that it is unsupported by Django
- fixed some text
- synchronized "wiki" subdirectory with the manually edited online Wiki

Automatic admin

---

README.rst

This settings is important to mention for users specially to avoid problems when the application don't need to communicate with Salesforce and salesforce is down or in maintenance.

Mention SF_LAZY_CONNECT settings in README.rst

---

salesforce/router.py

Data migrations don't work on a model base but the salesforce router always checks for model attributes.
Therefore RunSQL and RunPython are broken when using the salesforce router.
> Running migrations:
>   Rendering model states... DONE
>   Unapplying actionstream.0005_product_created...Traceback (most recent call last):
>   File "./manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/management …

Data migrations broken since 0.6.2

---

salesforce/backend/adapter.py
salesforce/testrunner/settings.py
salesforce/tests/test_ssl.py

This fix is important if the critical update "Require TLS 1.1 or higher for HTTPS connections" is activated in your organization SFDC Setup. (recommended)
Other possible solution is to only add a setting `SF_SSL` to project settings. [see our wiki amout SSL](https://github.com/django-salesforce/django-salesforce/wiki/SSL-TLS-settings-and-Salesforce.com)
I recommend version 0.6.2.5, because this could be blocking for organizations now.

Update for the critical update Salesforce required TLSv1.1+

---

salesforce/__init__.py

Django has implemented `__version__` string in 1.8 release, due to [PEP 396](https://www.python.org/dev/peps/pep-0396/) (deferred) - their issue 23442. It is not too late.
This is a simple solution. Maybe I summarize a new issue related to setup.py and write a new PR.

Added __version__ string #153

---

README.rst

The old URL pointed to a wrong article. It opens up a new page. Fixed the link.

Fixing SSL-TLS article link

---

README.rst
salesforce/backend/base.py
salesforce/backend/compiler.py
salesforce/backend/operations.py
salesforce/models.py
salesforce/router.py
salesforce/tests/test_integration.py
tests/tests.sh
tests/z_migrate_190/models.py
tests/z_migrate_190/settings.py
tests/z_migrate_190/test.sh
tests/z_migrate_190/tests.py

* Fixed the referenced issue number PR #191
* Support for setting primary keys on objects created using bulk_create() with Django 1.10+ (This feature was supported only by Postgres, but it is much more important with SF than with other databases due to missing transactions)

Fixed router bug with an alternate SF database. close #190

---

README.rst
salesforce/backend/query.py
salesforce/testrunner/settings.py
salesforce/tests/test_unit.py
tests/test_app_label/salesforce/apps.py
tests/test_app_label/salesforce/models.py
tests/test_app_label/salesforce/tests.py
tests/test_app_label/settings.py
tests/test_app_label/test.sh
tests/test_compatibility/settings.py
tests/test_mixin/settings.py

'salesforce' is now not required in INSTALLED_APPS.
It is much better then to require and check it (as was in the previous PR). It is even somewhat better to remove it from INSTALLED_APPS, because Django internal check works better. If 'salesforce' is registered and some user's app is not registered or uses a `SalesforceModel` in some unregistered place, such that the model would be correctly unregistered if it would be a `django.db.models.Model`, that model was still accepted like it would be a model in `'salesforce'` app. If 'salesforce' app is not registered, Django check works correctly and the user's model is reported unregistered.

Optional salesforce in installed apps

---

.travis.yml

As described in travis-ci/travis-ci#8363 there are some pyenv misconfigurations that were causing problems with our test run. This seems to be fixed with this branch.

Fix for #202, broken Python 3.5 support on Travis CI

---

.travis.yml

Updated to Ubuntu Xenial. These leverage pyenv and tox-pyenv. Currently still limited on Python 3.7.

Fixes to overall Python architecture for Travis

---

coverage_run.sh
salesforce/backend/query.py
salesforce/backend/test_helpers.py
salesforce/tests/test_integration.py

- Fixed the bug that depended on the locale.
- Written tests.
- The code "If-Modified-Since" was only due to the upstream bug in Salesforce [Composite Batch API PATCH call returns "entity failed If-Unmodified-Since test on update"...](https://success.salesforce.com/issues_view?id=a1p300000008aYNAAY&title=composite-batch-api-patch-call-returns-entity-failed-if-unmodified-since-test-on-update-but-no-if-unmodified-since-header-in-the-request) and should be removed now because the original required header is now completely ignored.

Fixed If-Unmodifed-Since #210

---

CHANGELOG.rst
README.rst
tox.ini

This was a typo in an old text from 2014, but the Model has been in salesforce.router since prehistory.

Fixed a very old typo in README

---

.travis.yml
CHANGELOG.rst
README.rst
salesforce/__init__.py
salesforce/backend/__init__.py
salesforce/backend/compiler.py
salesforce/backend/features.py
salesforce/backend/introspection.py
salesforce/backend/operations.py
salesforce/backend/utils.py
salesforce/dbapi/driver.py
salesforce/models_extend.py
salesforce/tests/test_integration.py
tests/inspectdb/slow_test.py
tox.ini

I suggest a new release soon.
this PR:
- Fix a small bug with Salesforce Winter '20 (Currently present only in preview sanboxes, but coming very soon) It is quite an important bug, but the impact is only for a `BusinessHours` object if it would be updated by Django. It is the only object where the `TimeField` is used or can be used.
- Fix django-salesforce for Django 3.0 (currently 3.0 alpha 1) Problems were only with `insert` command. It is as well the only important change related to database in Release notes 3.0.
I expect only documentation edit and release notes before the new release.

Support for Salesforce 47.0 Winter '20 and Django 3.0

---

salesforce/backend/manager.py
salesforce/backend/models_sql_query.py
salesforce/backend/query.py
salesforce/backend/utils.py
salesforce/models.py
salesforce/tests/test_unit.py
tests/test_default_db/test.sh
tests/test_managers/models.py
tests/test_managers/settings.py
tests/test_managers/test.sh
tests/test_managers/tests.py

Four commits are directly related to #253 (custom queryset on the default manager) and an important problem is solved, how to pass additional parameters to Salesforce methods
* Refactoring for clearer responsibility of objects
* Test for 253
* Added independent base manager
* Added a parameter `edge_updates` to enable updates on querysets that could be potentially unsafe and should be checked before use in production. The parameter `edge_updates` should be used only if the queryset is verified or similarly complex querysets are known compiled correctly. 
Additional parameters can be passed by a `sf(...)` method.
Example:
``` python
SomeModel.objects.sf(edge_updates=True).filter(related_model__some_field=value).update(...)
```
That parameters are ignored if the database backend is not …

Fix issue-253 and pass sf parameters to querysets

---

README.rst
salesforce/auth.py
salesforce/dbapi/driver.py

The last authenticator the completed everything on the refactored modular `auth.py` is the authentication by refresh token, class `salesforce.auth.RefreshTokenAuth`. It is briefly desribed in Wiki [Refresh Token Auth](https://github.com/django-salesforce/django-salesforce/wiki/Experimental-Features#refresh-token-auth). It allows to get a refresh token interactively by web browser by opening one link from console and copying another final link after authorization back to console. The refresh token written on the console should be saved to settings to remain authenticated also after restart.
I prefer to commit it not before v1.1

Authenticate by Refresh Token (replacement of password)

---

.travis.yml
CHANGELOG.rst
README.rst
salesforce/__init__.py
salesforce/backend/__init__.py
tests/test_mock/mocksf.py
tests/tooling/slow_test.py
tox.ini

We must release a new version because `salesforce/backend/__init__.py ` supported only Django 3.1 development releases, bun not the 3.1 final. A simple command "pip install django django-salesforce" would not work
It is my mistake that I thought first about some new code for August release or the support should have been added already to the late 1.1.
It is strange that we must release a new version, we have no new code except the fixed version check and we wanted to synchronize the version number in August with 3.1.
Even the unofficial [Refresh Token Authentication](https://github.com/django-salesforce/django-salesforce/wiki/Experimental-Features#refresh-token-auth) is in our v1.1
Nevertheless, I propose to publish 3.1 (or you can rewrite the last commit and CHANGELOG)

Version 3.1 compatible with Django 3.1 final

---

README.rst
salesforce/__init__.py
salesforce/auth.py
salesforce/backend/introspection.py
salesforce/backend/manager.py
salesforce/backend/operations.py
salesforce/dbapi/driver.py
salesforce/defaults.py
salesforce/fields.py
salesforce/management/commands/inspectdb.py
salesforce/testrunner/example/models.py
salesforce/tests/test_integration.py
salesforce/tests/test_utils.py
tests/inspectdb/slow_test.py
tests/inspectdb/tests.py
tests/tooling/slow_test.py
tox.ini

The first part is almost the same as the previous closed PR #276 Fix275, only with some fixed grammar typos and that Winter'21 is now available everywhere.
The second part is a series of fixes in order to can produce smaller `models.py` by `inspectdb`. A review of this part is desirable. I'm sure that the current solution is not perfect, but better than the previous state. 
A test passed by CI is not important enough. A review of better readability and usefulness of simplified output models.py is also important.

Fix inspectdb

---

.travis.yml
CHANGELOG.rst
README.rst
salesforce/__init__.py
salesforce/backend/__init__.py
salesforce/backend/compiler.py
salesforce/backend/features.py
salesforce/backend/introspection.py
salesforce/backend/manager.py
salesforce/backend/models_sql_query.py
salesforce/backend/query.py
salesforce/tests/test_unit.py
setup.cfg
tests/inspectdb/dependent_model/settings.py
tests/no_urls.py
tests/test_app_label/settings.py
tests/test_compatibility/settings.py
tests/test_migrate/settings.py
tests/test_mixin/settings.py
tests/tooling/slow_test.py
tox.ini

Django 4.1rc1 has been released on July 19. We can release django-salesforce v4.1 now.
* Add: Support for Django 4.1
* Add: Command ``inspectdb`` can introspect actual default values
of fields from a ``defaultValueFormula`` if it is a simple constant
like a number or a string.
* Fix: A default value ``DefaultedOnCreate(value)`` is no longer created
by ``inspectdb`` in favour of a simple ``value``. If a simple default value
can not be known then a generic ``DEFAULTED_ON_CREATE`` is still used rarely
for default values created by a complicated or unknown function only
on Salesforce side. #280
* Fix: Optionally don't use redundant table names before field names
if queried with ``.sf(minimal_aliases=True)``; important for some
special system objects #302
* Fix: Tests with the newest Django, …

Version v4.1 for Django 4.1

---

.travis.yml
CHANGELOG.rst
tox.ini

* Python 3.6 is after end of life. A new Ubuntu 22.04 LTS Jammy Jellyfish is an option on Travis.
* I test frequently also with Python 3.11 beta in tox locally.

Travis jammy

---

salesforce/backend/query.py
salesforce/router.py

Django caching to a 'default' database can be now used without adding a database router that would be otherwise necessary in a case of multiple databases. This is the usual way how tables for models with SalesforceModel are in `salesforce` database and other possible tables are in `default` database including a possible django cache table that has no explicit model or application

Support Django DatabaseCache with 'default' database by ModelRouter #315

---

CHANGELOG.rst
salesforce/__init__.py

CHANGELOG
* Add: Support for ``db_default`` field option in Django 5.0. It allows a seamless
support of the ``defaultedOnCreate`` counterpart in Salesforce.
* Add: Support for Salesforce API 60.0 Spring '24.
* Change: Values of ``FloatField`` are now really float, not Decimal as previously.
* Fix: Compatibility with the current django-debug-toolbar #322
* Fix: Introspection ``inspectdb`` of custom editable name fields #308
* Add: FloatField is used by ``inspectdb`` for some metadata with negative decimal places
that are new in API 60.0.
* Change: A license code is required also in the first half of lifetime of a LTS version
unless the AGPL licence is accepted.
Django 4.2 LTS will be unlocked together with unlocking 5.0 in August 2024
in Django-salesforce 5.1 release.
* Change: License …

 Release v5.0.1

---

.github/workflows/main.yml
CHANGELOG.rst
README.rst
coverage_run.sh
salesforce/__init__.py
salesforce/backend/__init__.py
salesforce/backend/compiler.py
salesforce/backend/models_lookups.py
salesforce/backend/operations.py
salesforce/testrunner/example/models.py
salesforce/testrunner/settings.py
salesforce/tests/test_documents.py
salesforce/tests/test_integration.py
setup.py
tests/clean_test_data.py
tox.ini

The main new features are in the **improved query compiler**
* Remove: the old Python 3.7
* Remove: the code for Django 2.0
* Fix: many issues in the query compiler in edge cases:
- fix a query with offset, but without a limit (NotImplementedError)
- fix a '__range' lookup on a field of custom foreign key object (SalesforceError)
- fix a '=null' lookup.  It worked probably always correctly, but the old implementation was different from  standard lookups. It made it impossible to distinguish it from unsupported queries
* Add: The query compiler is now much more precise. Most of unsupported queries will
write a warning before they are tried compiled. This is how users have
discovered some functional queries in the past.
No regression is known that a previously correct query would write a …

Prepare version 5.0.2

---

.github/workflows/main.yml
CHANGELOG.rst
README.rst
salesforce/__init__.py
salesforce/backend/__init__.py
salesforce/backend/enterprise.py
salesforce/backend/query.py
salesforce/backend/test_helpers.py
salesforce/backend/utils.py
salesforce/dbapi/__init__.py
salesforce/dbapi/driver.py
salesforce/models.py
salesforce/models_template.py
tox.ini

A release for Django 5.1
A new Django frequently uses rollback in tests. The message about ignored rollback was annoying in a test log. It will be now silent, but can be reported if
`settings.DATABASES['salesforce']['OPTIONS']['WARNING_ON_ROLLBACK'] == True`

Support Django 5.1
