coverage_run.sh, salesforce/fields.py, tests/inspectdb/slow_test.py, tox.ini
I think that it also simplifies the future development.
=> Fixed compatibility with Posgresql, interited AutoField, closed #90

README.rst, salesforce/__init__.py, salesforce/backend/base.py, salesforce/backend/client.py, salesforce/backend/compiler.py, salesforce/backend/creation.py, salesforce/backend/introspection.py, salesforce/backend/operations.py, salesforce/backend/query.py, salesforce/backend/validation.py, salesforce/models.py, salesforce/tests/test_utils.py, salesforce/utils.py, tox.ini
The pull request #100 is included here, but it was not enough to pass even 1% of tests with Django 1.8. One branch are Naoya Kanai's and my fixes to pass 80 % of tests. Other branch are fixes to pass all test in master with Django 1.7 before anything changed. After the merge I fixed the .count() method with Django 1.8 and the Readme. Six tests are still failing with Django 1.8 as noted in Readme.
=> Fixed a rough support for Django 1.8

salesforce/__init__.py, salesforce/backend/base.py, salesforce/backend/client.py, salesforce/backend/creation.py, salesforce/backend/introspection.py, salesforce/backend/operations.py, salesforce/backend/validation.py
Resolves #99. The import order becomes a bit messy - let me know if this works or not.
=> Resolve BaseDatabaseXXX import errors under Django 1.8

README.rst
Fixed Restructured Text syntax
=> Fixed README rst syntax #108

salesforce/fields.py, salesforce/testrunner/example/models.py, salesforce/tests/test_integration.py
Fixed makemigrations from migrations created by old django-salesforce. Closed #111
=>  Fixed makemigrations from old versions. Closed #111

README.rst, salesforce/backend/adapter.py, tox.ini
=> Configurable TLS. closes #109

salesforce/management/commands/inspectdb.py, salesforce/testrunner/settings.py
The inspectdb fix was just a small change to the pop() usage
=> Travis config fix, plus a minor inspectdb fix

salesforce/backend/compiler.py, salesforce/testrunner/example/models.py, salesforce/tests/test_integration.py
Reverts django-salesforce/django-salesforce#131
(see the comment about SOQL injection)
=> Revert "add range lookup functionality"

.coveragerc, README.rst, coverage_run.sh, salesforce/auth.py, salesforce/backend/base.py, salesforce/backend/compiler.py, salesforce/backend/introspection.py, salesforce/backend/query.py, salesforce/backend/subselect.py, salesforce/testrunner/example/models.py, salesforce/tests/test_auth.py, salesforce/tests/test_integration.py, salesforce/tests/test_utils.py, salesforce/utils.py, tests/inspectdb/slow_test.py, tests/inspectdb/tests.py, tox.ini
fixed 105 and 131, small fixes, refactored code  
Something is in release notes draft 0.6.1  
https://github.com/django-salesforce/django-salesforce/releases
=> Cumulative before v0.6.1

README.rst
Our README has been our only formal source of documentation for this project for some time, but it's been growing quite substantially, particularly as @hynekcer has plumbed some of the deepest depths of the SFDC realms. This is fantastic knowledge to have collected in one place, but most of it is increasingly unnecessary to first-time users.
I've started the process of moving some of the more esoteric content out of the README, and into the Wiki. I'm not really sure when this will hit `master`, but I would hope soon.
Any input or suggestions would be appreciated,
=> Documentation Cleanup (in progress)

requirements.txt, salesforce/__init__.py, salesforce/tests/test_ssl.py, setup.py, tox.ini
Fixed #156. Do you agree with a static version number independent on setuptools, easy_intall, pip, setup.py etc. issues?
=> Static version string 

salesforce/backend/query.py
This is probably a temporary solution. Therefore I don't replace the original "select_related" method, but a "simple_select_related" is added.
=> Fixed select_related issue #175 by simple_select_related

README.rst, coverage_run.sh, requirements.txt, salesforce/__init__.py, salesforce/backend/aggregates.py, salesforce/backend/base.py, salesforce/backend/client.py, salesforce/backend/compiler.py, salesforce/backend/creation.py, salesforce/backend/driver.py, salesforce/backend/introspection.py, salesforce/backend/operations.py, salesforce/backend/query.py, salesforce/backend/validation.py, salesforce/management/commands/inspectdb.py, salesforce/models.py, salesforce/router.py, salesforce/testrunner/settings.py, salesforce/tests/test_integration.py, tox.ini
The first part merged from development branch:
* fixed test to work with coverage
* fixed test to work if the first found user is inactive
* removed Django 1.7 and related code (I started with, otherwise it was problematic to arrange related commits together.
(I should ask you before the next commit [73fb48ef](https://github.com/hynekcer/django-salesforce/commit/73fb48eff03c190a31aa261b57b0e353eddea122) More info at the link that only in git. That will be eventually part of a next PR.)
=> Obsoleted django17

README.rst, coverage_run.sh, requirements.txt, salesforce/__init__.py, salesforce/backend/base.py, salesforce/backend/compiler.py, salesforce/backend/introspection.py, salesforce/backend/manager.py, salesforce/backend/query.py, salesforce/backend/schema.py, salesforce/tests/test_doc_tests.py, salesforce/tests/test_integration.py, setup.py, tests/inspectdb/slow_test.py, tox.ini
Based on parts from #182 (tuky - Tobias Krönke)
A new release is useful, even that it is like RC version (release candidatus) if used with  Django 1.11 and a warning about it is written.
=> Fixed for Django 1.11

README.rst, salesforce/testrunner/settings.py, salesforce/tests/test_integration.py
* Clarified why some install steps are important. Reordered, because INSTALLED_APPS are important only with 'inspectdb'. Please check the text and also the whole Quick Start and edit. Some terms are now used first before they are explained, but I can not review readability or improve .
* Explained that SalesforceModel is an alias for salesforce.models.Model
* Small improvement in tests
=> Explain installed apps

.travis.yml, README.rst, salesforce/__init__.py, salesforce/backend/compiler.py, salesforce/backend/introspection.py, salesforce/backend/manager.py, salesforce/backend/query.py, salesforce/fields.py, salesforce/management/commands/inspectdb.py, salesforce/models.py, salesforce/testrunner/settings.py, salesforce/testrunner/urls.py, salesforce/tests/test_integration.py, setup.py, tests/inspectdb/slow_test.py, tests/inspectdb/test.sh, tox.ini
Django versions from 1.10 to 2.1 are supported in an almost equal quality, but still less than it was with Django 1.9. (version that is currently unsupported)
Included the first two commits from #216
=> Fixed for Django 2.1

salesforce/backend/query.py, salesforce/tests/test_integration.py
Applying #206 commits against latest master with Travis fixes.
=> Fixed PR #206 by rebase against master

salesforce/backend/query.py, salesforce/tests/test_integration.py
Reverts django-salesforce/django-salesforce#223
Incompatible code. I left it open only for later inspiration. I'm sorry that I did not commented it.
=> Revert "Fixed PR #206 by rebase against master"

CHANGELOG.rst, pylintrc, salesforce/__init__.py, salesforce/auth.py, salesforce/backend/compiler.py, salesforce/backend/introspection.py, salesforce/backend/schema.py, salesforce/backend/utils.py, salesforce/dbapi/exceptions.py, salesforce/router.py, salesforce/testrunner/example/views.py, salesforce/tests/test_integration.py, tox.ini
I want to release a new version 0.8.1, mainly in order to fix the regression #226, that was reported recently again.
The best day will be on Monday, May 20th, that date is in the changelog.
=> Version 0.8.1

CHANGELOG.rst, README.rst, salesforce/backend/introspection.py, salesforce/backend/utils.py, salesforce/testrunner/example/models.py, salesforce/tests/test_integration.py
* Fix objects.all().delete()
* Support new introspection methods (not frequently useful)
=> Fix objects.all().delete()

.travis.yml, CHANGELOG.rst, README.rst, coverage_run.sh, salesforce/backend/__init__.py, salesforce/backend/base.py, salesforce/backend/compiler.py, salesforce/backend/features.py, salesforce/backend/introspection.py, salesforce/backend/operations.py, salesforce/backend/test_helpers.py, salesforce/backend/utils.py, salesforce/dbapi/driver.py, salesforce/dbapi/exceptions.py, salesforce/fields.py, salesforce/management/commands/inspectdb.py, setup.py, tests/t_debug_toolbar/settings.py, tests/t_debug_toolbar/test.sh, tests/t_debug_toolbar/tests.py, tests/t_debug_toolbar/urls.py, tests/t_debug_toolbar/views.py, tox.ini
I added three additional commit to easier reproduce the remaining problem issue #247 
after the older two commits where I fixed what could be reproduced.
* Updaded test environment (for Travis)
* Test insert, update and delete with django-debug-toolbar (can be used also for manual testing)
* Implemented EXPLAIN command (usable in django-debug-toolbar)
The EXPLAIN command is really a maximal possible support for Django debug toolbar.
See [Salesforce documentation about their EXPLAN command](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_query_explain.htm)
I will crate a new branch until the issue is fixed enough. (I found also some smaller issues by manual testing in example admin on a huge raw model from inspectdb.)
=> Debug toolbar

CHANGELOG.rst, requirements.txt, salesforce/__init__.py, salesforce/auth.py, salesforce/backend/compiler.py, salesforce/backend/introspection.py, salesforce/backend/models_sql_query.py, salesforce/backend/query.py, salesforce/backend/utils.py, salesforce/dbapi/__init__.py, salesforce/dbapi/common.py, salesforce/dbapi/driver.py, salesforce/dbapi/test_helpers.py, salesforce/models.py, salesforce/testrunner/example/models.py, salesforce/testrunner/settings.py, salesforce/tests/test_bulk.py, salesforce/tests/test_integration.py, tests/test_mock/mocksf.py, tests/test_mock2/test_rec.py
* Add: Implement queryset.bulk_update() method #236
* Fix: SOQL command in queryset.raw() is supported case insensitive
=> Implement bulk_update()

.travis.yml, mypy.ini, salesforce/backend/introspection.py, salesforce/backend/manager.py, salesforce/backend/models_lookups.py, salesforce/backend/test_helpers.py, salesforce/dbapi/subselect.py, salesforce/testrunner/settings.py, salesforce/tests/test_integration.py, tests/mypy.sh, tests/no_django_dbapi/test.py, tests/test_managers/tests.py, tox.ini
Configurable SF_MAX_INSPECTDB_PICKLIST_LENGTH   - in the last commit
=> Configurable picklist length

README.rst, salesforce/backend/enterprise.py
-  Readme: Add test result badge by Github to home page (it is visible now in the branch "docs")
What to do with Travis? It was better that Github Actions, but...
Some readme will be still beneficial.
=> Readme: test result badge by Github

README.rst
=> Document the need to enable Allow OAuth Username-Password Flows

salesforce/auth.py
This is a hotfix for a reported network issue until that error can be reproduced:
Error 401 after some inactivity and after a message
"RemoteDisconnected: Remote end closed connection without response"
The final fix can be different when more information about the issue is found.
=> Fix for RemoteDisconnected issue in Login
